# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'training-settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(741, 376)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.trainingNameLabel = QtWidgets.QLabel(Dialog)
        self.trainingNameLabel.setObjectName("trainingNameLabel")
        self.gridLayout.addWidget(self.trainingNameLabel, 0, 0, 1, 1)
        self.trainingNameInput = QtWidgets.QLineEdit(Dialog)
        self.trainingNameInput.setObjectName("trainingNameInput")
        self.gridLayout.addWidget(self.trainingNameInput, 0, 1, 1, 1)
        self.darknetPathLabel = QtWidgets.QLabel(Dialog)
        self.darknetPathLabel.setObjectName("darknetPathLabel")
        self.gridLayout.addWidget(self.darknetPathLabel, 1, 0, 1, 1)
        self.darknetPathInput = QtWidgets.QLineEdit(Dialog)
        self.darknetPathInput.setObjectName("darknetPathInput")
        self.gridLayout.addWidget(self.darknetPathInput, 1, 1, 1, 1)
        self.darknetBtn = QtWidgets.QPushButton(Dialog)
        self.darknetBtn.setStyleSheet("color: white;\n"
"border-style: none;\n"
"border-width: none;\n"
"border-radius: 0px;\n"
"border-color: black;\n"
"font:bold 12px;\n"
"min-width: 6rem;\n"
"padding: 6px;\n"
"background-color: grey;")
        self.darknetBtn.setObjectName("darknetBtn")
        self.gridLayout.addWidget(self.darknetBtn, 1, 2, 1, 1)
        self.configPathLabel = QtWidgets.QLabel(Dialog)
        self.configPathLabel.setObjectName("configPathLabel")
        self.gridLayout.addWidget(self.configPathLabel, 2, 0, 1, 1)
        self.configPathInput = QtWidgets.QLineEdit(Dialog)
        self.configPathInput.setObjectName("configPathInput")
        self.gridLayout.addWidget(self.configPathInput, 2, 1, 1, 1)
        self.configBtn = QtWidgets.QPushButton(Dialog)
        self.configBtn.setStyleSheet("color: white;\n"
"border-style: none;\n"
"border-width: none;\n"
"border-radius: 0px;\n"
"border-color: black;\n"
"font:bold 12px;\n"
"min-width: 6rem;\n"
"padding: 6px;\n"
"background-color: grey;")
        self.configBtn.setObjectName("configBtn")
        self.gridLayout.addWidget(self.configBtn, 2, 2, 1, 1)
        self.configPathLabel_2 = QtWidgets.QLabel(Dialog)
        self.configPathLabel_2.setObjectName("configPathLabel_2")
        self.gridLayout.addWidget(self.configPathLabel_2, 3, 0, 1, 1)
        self.weightPathInput = QtWidgets.QLineEdit(Dialog)
        self.weightPathInput.setText("")
        self.weightPathInput.setObjectName("weightPathInput")
        self.gridLayout.addWidget(self.weightPathInput, 3, 1, 1, 1)
        self.weightBtn = QtWidgets.QPushButton(Dialog)
        self.weightBtn.setStyleSheet("color: white;\n"
"border-style: none;\n"
"border-width: none;\n"
"border-radius: 0px;\n"
"border-color: black;\n"
"font:bold 12px;\n"
"min-width: 6rem;\n"
"padding: 6px;\n"
"background-color: grey;")
        self.weightBtn.setObjectName("weightBtn")
        self.gridLayout.addWidget(self.weightBtn, 3, 2, 1, 1)
        self.dataPathLabel = QtWidgets.QLabel(Dialog)
        self.dataPathLabel.setObjectName("dataPathLabel")
        self.gridLayout.addWidget(self.dataPathLabel, 4, 0, 1, 1)
        self.dataPathInput = QtWidgets.QLineEdit(Dialog)
        self.dataPathInput.setObjectName("dataPathInput")
        self.gridLayout.addWidget(self.dataPathInput, 4, 1, 1, 1)
        self.dataBtn = QtWidgets.QPushButton(Dialog)
        self.dataBtn.setStyleSheet("color: white;\n"
"border-style: none;\n"
"border-width: none;\n"
"border-radius: 0px;\n"
"border-color: black;\n"
"font:bold 12px;\n"
"min-width: 6rem;\n"
"padding: 6px;\n"
"background-color: grey;")
        self.dataBtn.setObjectName("dataBtn")
        self.gridLayout.addWidget(self.dataBtn, 4, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStyleSheet("color: white;\n"
"border-style: none;\n"
"border-width: none;\n"
"border-radius: 0px;\n"
"border-color: black;\n"
"font:bold 12px;\n"
"min-width: 6rem;\n"
"padding: 6px;\n"
"background-color: grey;")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Training Settings"))
        self.label.setText(_translate("Dialog", "Please set the following settings"))
        self.trainingNameLabel.setText(_translate("Dialog", "Training Name: "))
        self.darknetPathLabel.setText(_translate("Dialog", "Darknet Path: "))
        self.darknetPathInput.setPlaceholderText(_translate("Dialog", "Enter path to darkent folder"))
        self.darknetBtn.setText(_translate("Dialog", "Select"))
        self.configPathLabel.setText(_translate("Dialog", "Config Path: "))
        self.configPathInput.setPlaceholderText(_translate("Dialog", "Enter path to .cfg file"))
        self.configBtn.setText(_translate("Dialog", "Select"))
        self.configPathLabel_2.setText(_translate("Dialog", "Weight Path: "))
        self.weightPathInput.setPlaceholderText(_translate("Dialog", "Enter path to .weights file"))
        self.weightBtn.setText(_translate("Dialog", "Select"))
        self.dataPathLabel.setText(_translate("Dialog", "Data Path: "))
        self.dataPathInput.setPlaceholderText(_translate("Dialog", "Enter path to .data file"))
        self.dataBtn.setText(_translate("Dialog", "Select"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
